{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
  annotations:
    # Tell Envoy to expose Prometheus metrics
    gateway.envoyproxy.io/enable-prometheus: "true"
spec:
  gatewayClassName: {{ .Values.gateway.className | default "envoy" }}
  listeners:
    - name: http
      protocol: HTTP
      port: {{ .Values.gateway.port | default 80 }}
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
