# templates/nginx-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nginx
data:
  default.conf: |
    server {
        listen 3001;
        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://{{ .Release.Name }}-backend:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
