apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  JWT_SECRET: {{ .Values.backend.jwtSecret | b64enc | quote }}
  ADMIN_PASSWORD: {{ .Values.backend.adminPassword | b64enc | quote }}
