{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name | default (printf "%s-backend" .Release.Name) }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
{{- end }}
